### ISSUE TITLE
README links to docs, and docs landing page

### ISSUE THREAD

**Issue by dbuscombe-usgs** [CameronBodine/PINGMapper#32]
Currently, the [link to the docs on the README](https://github.com/CameronBodine/PINGMapper#website) goes to the page on the binary [data structure](https://github.com/CameronBodine/PINGMapper/blob/main/docs/BinaryStructure.md).

I think a better approach would be to create a documentation "landing page" that explains the overall purpose in a concise way (perhaps use material from your proposal and paper), then links to the 3 subpages 1) raw data/export, 2) georecti, 3) binary data

**Comment by CameronBodine** [comment]
I'm closing this as documentation is now found on PING-Mapper's webpage: https://cameronbodine.github.io/PINGMapper/. Documentation will be tracked with #13.
