### ISSUE TITLE
Got an exception when Running "test_PINGMapper.py 1“

### ISSUE THREAD

**Issue by gushangzao007** [CameronBodine/PINGMapper#85]
I try to run the test function to verify my installation, it got several errors. 
error message like that:   AttributeError: module 'numpy' has no attribute 'int'.
[error.txt](https://github.com/CameronBodine/PINGMapper/files/11980821/error.txt)

**Comment by gushangzao007** [comment]
by the way , expected data has been generated. I'm not sure if those data is ok.
![image](https://github.com/CameronBodine/PINGMapper/assets/11475854/0196291f-5b90-4984-ad90-61123fa6a651)

**Comment by CameronBodine** [comment]
Can you provide the full error from the console? Thanks!

**Comment by gushangzao007** [comment]
full error is in the attached file within my first post, can you see it?

**Comment by CameronBodine** [comment]
Sorry I missed it. Ok, just posted an update. Run `git pull` and try the test again. Please report back!

**Comment by CameronBodine** [comment]
@gushangzao007 was your issue resolved?

**Comment by gushangzao007** [comment]
sorry, have not yet, I've changed my solution for my hobby project, thanks for your advice about how to use SL3Reader to generate a point cloud, :)

**Comment by CameronBodine** [comment]
Great I will close the issue then.
