### ISSUE TITLE
Problem with Tensorflow Module upon Attempted Update

### ISSUE THREAD

**Issue by AdrianPinchbeck** [CameronBodine/PINGMapper#92]
I attempted to update to new version, but seemed to have an issue with updating the environment.  I tried a new install in a different directory using the libmamba solver, but also had issues, and installed using classic instead.  Unfortunately I now seem to be having a problem with the module tensorflow.keras.  I've been down a number of rabbit holes trying to correct the issue without success.  Just wondered if you have any pointers?
Adrian
![image](https://github.com/CameronBodine/PINGMapper/assets/121804798/5d63b0e6-3b48-45c5-89ec-bac71fc37bb9)

**Comment by CameronBodine** [comment]
Thanks for reporting Adriane. Do you remember what the issues were with libmamba?

It looks like your environment is either missing Keras or there is a mismatch in versions between tensorflow and keras. https://stackoverflow.com/questions/73796400/error-no-module-named-tensorflow-keras

Can you run 'conda list' in the ping environment and check that keras and tensorflow versions match? And report the output please.

**Comment by AdrianPinchbeck** [comment]
Sorry, I don't recall the actual issue, I did attempt to record some of the screen errors, but the capture didn't work!  Conda List reports thus:
![image](https://github.com/CameronBodine/PINGMapper/assets/121804798/717a9c23-7594-4012-9aab-4b0d3d628c95)

and Keras:
![image](https://github.com/CameronBodine/PINGMapper/assets/121804798/de66b6b3-38d2-4b00-9e11-1caa6a16a453)

**Comment by CameronBodine** [comment]
Ok give this a try:
```
conda install keras=2.13.0
```

If that doesn't work, try removing the ping environment with
```
conda remove --name ping --all
```

then clean miniconda
```
conda clean --all
```

then update miniconda
```
conda update -n base conda
```

clean again
```
conda clean --all
```

update pip
```
pip install --upgrade pip
```

get libmamba up and running again
```
conda install -n base conda-libmamba-solver
conda config --set solver libmamba
```

then try reinstalling ping
```
conda env create --file conda/PINGMapper.yml
```


If you can keep track of errors as they arise and report them, that will help a lot! Thanks for helping me debug!!!!

**Comment by CameronBodine** [comment]
Hmm, give this a try:

conda install pip

You should have write access to that folder. Strange indeed!

**Comment by AdrianPinchbeck** [comment]
Just realised that I forgot the second clean --all after updating conda.  I could clean again before your above conda install pip?

**Comment by AdrianPinchbeck** [comment]
Checked the Attributes for the Site Packages folder and found that it is marked up as 'Read Only', together with all it's sub-directories.  I'm going to uncheck the Attributes bullet, and try pip install --upgrade pip again...  Wish me luck!

**Comment by AdrianPinchbeck** [comment]
Having no luck so far!  Changing attributes via Windows, making sure all permissions etc. are available to the top of the tree, and having default administrator rights anyway, I'm running in to failure so far.  Attributes are checked in grey for Anaconda3 directory and sub-directories (not black), further up the tree in black. Unfortunately I don't have much time this week to progress through the issue during the day, but I'll keep you informed of progress tomorrow evening again.  Almost time for bed now, but thanks again for your help to date.

**Comment by CameronBodine** [comment]
One thing could try is uninstalling miniconda and reinstalling, making sure to select Install for: Just Me (recommended). Also, maybe you are using Anaconda instead of miniconda? I have had a lot more success with Miniconda. Keep me posted and I will help as much as possible!

![image](https://github.com/CameronBodine/PINGMapper/assets/54146655/aedd5907-6f53-4477-b60a-4ba0829ad05a)

**Comment by AdrianPinchbeck** [comment]
I've been using the full Anaconda3 installation, so potentially run into some conflict/s somewhere.  Have uninstalled it, and currently installing Miniconda3 as above...

**Comment by CameronBodine** [comment]
My bad. Try running `git fetch`. Also, there is a simple GUI you could try out, if interested. Run either `python gui_main.py` or `python gui_main_batchDirectory.py`.

**Comment by AdrianPinchbeck** [comment]
Will take a look at the GUI once have it working if that's okay!! Similar error results after running git fetch (didn't try remove cmocean #92):
![image](https://github.com/CameronBodine/PINGMapper/assets/121804798/1b49ce2d-32b9-4f24-8262-6ecf2349eec1)

**Comment by AdrianPinchbeck** [comment]
PINGMapper test folder:
![image](https://github.com/CameronBodine/PINGMapper/assets/121804798/c31ef80f-b5c8-46b5-8b56-30392098f618)

**Comment by CameronBodine** [comment]
Ok that helps. Looks like it isn't updating. Go ahead and delete the folder, then download the latest version with `git clone --depth 1 https://github.com/CameronBodine/PINGMapper`. You may need to update the environment again with this `conda env update --file conda/PINGMapper.yml --prune`.

**Comment by AdrianPinchbeck** [comment]
I've placed hash on line 39 within class_rectObj.py to form a comment, then saved, but still getting same error when running the test:
 
![image](https://github.com/CameronBodine/PINGMapper/assets/121804798/9816ed68-1218-4cee-8a9f-08edf31aa100)

**Comment by AdrianPinchbeck** [comment]
Ah okay, I may place it in a new folder altogether.

**Comment by CameronBodine** [comment]
I was also wondering if you may be editing one version of PINGMapper then running a version in a different folder.

**Comment by AdrianPinchbeck** [comment]
I did wonder that myself, but checking the navigation all seemed to correspond correctly.  Might be wise to relocate any old directories within a separate archive directory to change the path for better housekeeping?

**Comment by AdrianPinchbeck** [comment]
The test is running.  I did notice a message during the mosaic section that I'll check over.
We're back in business though - I may need a little lie down!

![image](https://github.com/CameronBodine/PINGMapper/assets/121804798/a55d23d4-ca05-4252-881c-b2f500cbdc9b)

**Comment by CameronBodine** [comment]
Good to hear! I'm sorry it was such a pain! Yes, I need to get that warning taken care of. It won't affect anything for you though.

**Comment by AdrianPinchbeck** [comment]
Thanks for all your input Cameron, it must have been a pain for you too!  Yes, both mosaics seem to have been created successfully.  I'll probably go through it all in more detail tomorrow, so I'll go now and have a stiff drink before bed - rum.  Thanks again, and I'm planning to place a good result post on here in connection with that ghost gear I mapped the other week....

**Comment by CameronBodine** [comment]
It's always an adventure getting folks up and running! Looking forward to your post! Cheers!

I'll close this issue now. Please make another if needed.
