### ISSUE TITLE
batch process error

### ISSUE THREAD

**Issue by jasonfischer** [CameronBodine/PINGMapper#97]
Hi Cam,

I've been enjoying the recent version of PINGMapper, but I'm having some difficulty processing my sonar files in batch. I'm able to process a single sonar file fine, but with the batch processing script my colleague and I are both getting the same error. A text file with my python session and error message is attached. Everything seems to run fine until the end of the script when processing on file is wrapping up and we receive a ValueError: I/O operation on closed file. We suspect it is probably something simple to do with the batch processing script, but unfortunately, neither of us are that savvy with python, so our troubleshooting hasn't yielded much progress. Would you mind taking a look at the session output and helping us troubleshoot?

Also, a bit of info. on my PC, if it helps: I'm using Windows 10, a 12th Gen Intel(R) Core(TM) i9-12950HX   2.30 GHz processor, and 64GB of RAM. For reproducibility, I used batch processing script and data that comes with PINGMapper for the session attached below. 

Thanks,
Jason

[pingMapper_batchProcessError.txt](https://github.com/CameronBodine/PINGMapper/files/12621637/pingMapper_batchProcessError.txt)

**Comment by CameronBodine** [comment]
Hey Jason!
Thanks for posting the issue and the log file. Silly mistake on my part. I think I fixed it, so go ahead and update with:

```
conda env update --file conda/PINGMapper.yml --prune
```

Let me know how it goes.

It was really great meeting you in person at AFS! You guys are doing some really great work!
Cam

**Comment by jasonfischer** [comment]
Thanks Cam,

I have the batch processing working now! I ran the update, following your directions on the PINGMapper page, although the .py files that you updated didn't get pushed to my computer. I ended up just downloading those and replacing the old files in my PINGMapper folder, which seems to have done the trick.

**Comment by CameronBodine** [comment]
Oh yea, you have to run a 'git stash' first. Sorry about that. Very glad it worked! Keep me posted on how the maps come out. Curious how they compare to your manual maps.

I'll close as complete.
